version: "3"

services:
  stock-day:
    build: ./stock-day
    image: stock/stock-day
    network_mode: "host"
    restart: always
    ports:
      - "8890:8890"
    environment:
      - TZ=Asia/Shanghai
      - server.port=8890
      - spring.cloud.config.profile=sit
      - "eureka.client.service-url.defaultZone=http://register-center:8781/eureka/"
  gateway-center:
    build: ./gateway-center
    image: stock/gateway-center
    network_mode: "host"
    restart: always
    ports:
      - "8880:8880"
    environment:
      - TZ=Asia/Shanghai
      - spring.cloud.config.profile=sit
      - "eureka.client.service-url.defaultZone=http://register-center:8781/eureka/"
  log-center:
    build: ./log-center
    image: stock/log-center
    network_mode: "host"
    restart: always
    ports:
      - "8895:8895"
    environment:
      - TZ=Asia/Shanghai
      - spring.cloud.config.profile=sit
      - "eureka.client.service-url.defaultZone=http://register-center:8781/eureka/"
  stocket-center:
    build: ./socket-center
    image: stock/socket-center
    network_mode: "host"
    restart: always
    ports:
      - "8898:8898"
    environment:
      - TZ=Asia/Shanghai
      - spring.cloud.config.profile=sit
      - "eureka.client.service-url.defaultZone=http://register-center:8781/eureka/"