spring:
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
logging:
  level:
    root: info
    com.stock: debug
  file: logs/${spring.application.name}.log
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    cms:
      path: /api-w/**
      serviceId: cms-web
    day:
      path: /api-d/**
      serviceId: stock-day
    log:
      path: /api-l/**
      serviceId: log-center
  host:
    connect-timeout-millis: 10000001
    socket-timeout-millis: 60000001
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
ribbon:
  ReadTimeout: 10000001
  ConnectTimeout: 10000001
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000001