spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_helper?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
logging:
  level:
    root: info
    com.stock.stockday.mapper: debug
  file: logs/${spring.application.name}.log
mybatis-plus:
  type-aliases-package: com.stock.stockday.entity
  mapper-locations: classpath:/mybatis-mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: UUID
    refresh: true
ribbon:
  ReadTimeout: 600000001
  ConnectTimeout: 600000001
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000001
stock-url: http://quotes.money.163.com/service/chddata.html?code=#code#&start=#beginTime#&end=#endTime#&fields=TCLOSE;HIGH;LOW;TOPEN;LCLOSE;CHG;PCHG;TURNOVER;VOTURNOVER;VATURNOVER;TCAP;MCAP
stock-science-url: http://qt.gtimg.cn/q=ff_#code#
stock-url2: http://hq.sinajs.cn/list=#code#