#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/healthcare?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: 12qwaszx
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#      connection-test-query: SELECT 1
#  mvc:
#    servlet:
#      load-on-startup: 1
#  aop:
#    proxy-target-class: true
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#    sender:
#      type: web
#logging:
#  level:
#    root: info
#    com.suibuaa: debug
#  file: logs/${spring.application.name}.log
#mybatis-plus:
#  type-aliases-package: com.suibuaa.healthcare.device.entity
#  mapper-locations: classpath:/mybatis-mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#  global-config:
#    db-config:
#      id-type: UUID
#    refresh: true
#ribbon:
#  ReadTimeout: 10001
#  ConnectTimeout: 10001
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60001
#first-generation:
#  latest-blood-pressure-url: http://139.129.215.7:8080/ripc-sz/api/v1/bp
#  time-blood-pressure-url: http://139.129.215.7:8080/ripc-sz/api/v1/bp-list
#  latest-train-url: http://139.129.215.7:8080/ripc-sz/api/v1/train
#  time-train-url: http://139.129.215.7:8080/ripc-sz/api/v1/train-list