package com.stock.stockday.util;

import com.stock.stockday.entity.StockDayYanPan24;
import com.stock.stockday.entity.StockDayYanPan33;
import com.stock.stockday.entity.StockDayYanPan42;
import com.stock.stockday.entity.StockDayYanPanBenpan;
import com.stock.stockday.entity.StockDayYanPanChunJishu;
import com.stock.stockday.entity.StockDayYanPanChunTuxing;
import com.stock.stockday.entity.StockDayYanPanDapan;
import com.stock.stockday.entity.StockDayYanPanUpUp;
import com.stock.stockday.entity.StockDayYanPanZhuYanJiShu;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import static com.stock.stockday.util.getBigDecimalUtil.getBigDecimal;

public class GetEntity {
    public static StockDayYanPanUpUp getUpUpentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanUpUp stockDayYanPanUpUp1 = new StockDayYanPanUpUp();
        stockDayYanPanUpUp1.setLiangXian(upups[0]);
        stockDayYanPanUpUp1.setSanXian(upups[1]);
        stockDayYanPanUpUp1.setSiXian(upups[2]);
        stockDayYanPanUpUp1.setWuXian(upups[3]);
        stockDayYanPanUpUp1.setKdj(upups[4]);
        stockDayYanPanUpUp1.setMacd(upups[5]);
        stockDayYanPanUpUp1.setQuantityMa(upups[6]);
        stockDayYanPanUpUp1.setPriceMa(upups[7]);
        String[] lingsi = upups[8].split(",");
        stockDayYanPanUpUp1.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanUpUp1.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanUpUp1.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanUpUp1.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanUpUp1.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanUpUp1.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanUpUp1.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanUpUp1.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanUpUp1.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanUpUp1.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanUpUp1.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanUpUp1.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanUpUp1.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanUpUp1.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanUpUp1.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanUpUp1.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanUpUp1.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanUpUp1.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanUpUp1.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanUpUp1.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanUpUp1.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanUpUp1.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanUpUp1.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanUpUp1.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanUpUp1.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanUpUp1.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanUpUp1.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanUpUp1.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPanUpUp1.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPanUpUp1.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[62].split(",");
        stockDayYanPanUpUp1.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[63].split(",");
        stockDayYanPanUpUp1.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanUpUp1;
    }

    public static StockDayYanPan24 get24entity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPan24 stockDayYanPan24 = new StockDayYanPan24();
        stockDayYanPan24.setDangRi(upups[0]);
        stockDayYanPan24.setSanXian(upups[1]);
        stockDayYanPan24.setKdj(upups[2]);
        stockDayYanPan24.setMacd(upups[3]);
        stockDayYanPan24.setQuantityMa(upups[4]);
        stockDayYanPan24.setPriceMa(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPan24.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPan24.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPan24.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPan24.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPan24.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPan24.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPan24.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPan24.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPan24.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPan24.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPan24.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPan24.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPan24.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPan24.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPan24.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPan24.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPan24.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPan24.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPan24.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPan24.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPan24.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPan24.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPan24.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPan24.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPan24.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPan24.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPan24.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPan24.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPan24.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPan24.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPan24.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPan24.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPan24.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPan24.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPan24.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPan24.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPan24.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPan24.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPan24.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPan24.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPan24.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPan24.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPan24.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPan24.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPan24.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPan24.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPan24.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPan24.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPan24.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPan24.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPan24.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPan24.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPan24.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPan24.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPan24.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPan24.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPan24;
    }

    public static StockDayYanPan33 get33entity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPan33 stockDayYanPan33 = new StockDayYanPan33();
        stockDayYanPan33.setDangRi(upups[0]);
        stockDayYanPan33.setLiangXian(upups[1]);
        stockDayYanPan33.setSanXian(upups[2]);
        stockDayYanPan33.setKdj(upups[3]);
        stockDayYanPan33.setMacd(upups[4]);
        stockDayYanPan33.setPriceMa(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPan33.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPan33.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPan33.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPan33.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPan33.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPan33.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPan33.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPan33.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPan33.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPan33.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPan33.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPan33.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPan33.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPan33.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPan33.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPan33.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPan33.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPan33.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPan33.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPan33.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPan33.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPan33.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPan33.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPan33.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPan33.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPan33.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPan33.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPan33.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPan33.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPan33.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPan33.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPan33.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPan33.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPan33.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPan33.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPan33.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPan33.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPan33.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPan33.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPan33.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPan33.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPan33.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPan33.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPan33.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPan33.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPan33.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPan33.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPan33.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPan33.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPan33.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPan33.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPan33.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPan33.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPan33.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPan33.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPan33.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPan33;
    }

    public static StockDayYanPan42 get42entity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPan42 stockDayYanPan42 = new StockDayYanPan42();
        stockDayYanPan42.setDangRi(upups[0]);
        stockDayYanPan42.setLiangXian(upups[1]);
        stockDayYanPan42.setSanXian(upups[2]);
        stockDayYanPan42.setSiXian(upups[3]);
        stockDayYanPan42.setKdj(upups[4]);
        stockDayYanPan42.setPriceMa(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPan42.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPan42.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPan42.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPan42.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPan42.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPan42.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPan42.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPan42.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPan42.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPan42.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPan42.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPan42.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPan42.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPan42.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPan42.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPan42.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPan42.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPan42.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPan42.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPan42.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPan42.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPan42.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPan42.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPan42.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPan42.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPan42.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPan42.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPan42.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPan42.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPan42.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPan42.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPan42.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPan42.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPan42.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPan42.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPan42.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPan42.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPan42.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPan42.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPan42.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPan42.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPan42.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPan42.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPan42.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPan42.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPan42.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPan42.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPan42.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPan42.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPan42.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPan42.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPan42.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPan42.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPan42.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPan42.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPan42.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPan42;
    }

    public static StockDayYanPanBenpan getBenpanentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanBenpan stockDayYanPanBenpan = new StockDayYanPanBenpan();
        stockDayYanPanBenpan.setBenPiao1(upups[0]);
        stockDayYanPanBenpan.setBenPiao2(upups[1]);
        stockDayYanPanBenpan.setBenPiao3(upups[2]);
        stockDayYanPanBenpan.setBenPiao5(upups[3]);
        stockDayYanPanBenpan.setBenPiao13(upups[4]);
        stockDayYanPanBenpan.setBenPiao20(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPanBenpan.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanBenpan.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanBenpan.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanBenpan.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanBenpan.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanBenpan.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanBenpan.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanBenpan.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanBenpan.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanBenpan.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanBenpan.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanBenpan.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanBenpan.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanBenpan.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanBenpan.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanBenpan.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanBenpan.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanBenpan.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanBenpan.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanBenpan.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanBenpan.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanBenpan.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanBenpan.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanBenpan.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanBenpan.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanBenpan.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanBenpan.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanBenpan.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanBenpan.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanBenpan.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanBenpan.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanBenpan.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanBenpan.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanBenpan.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanBenpan.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanBenpan.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanBenpan.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanBenpan.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanBenpan.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanBenpan.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanBenpan.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanBenpan.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanBenpan.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanBenpan.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanBenpan.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanBenpan.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanBenpan.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanBenpan.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanBenpan.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanBenpan.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanBenpan.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanBenpan.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanBenpan.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanBenpan.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPanBenpan.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPanBenpan.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanBenpan;
    }

    public static StockDayYanPanDapan getDaPanentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanDapan stockDayYanPanDaPan1 = new StockDayYanPanDapan();
        stockDayYanPanDaPan1.setDaPan1(upups[0]);
        stockDayYanPanDaPan1.setDaPan2(upups[1]);
        stockDayYanPanDaPan1.setDaPan3(upups[2]);
        stockDayYanPanDaPan1.setDaPan5(upups[3]);
        stockDayYanPanDaPan1.setDaPan13(upups[4]);
        stockDayYanPanDaPan1.setDaPan20(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPanDaPan1.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanDaPan1.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanDaPan1.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanDaPan1.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanDaPan1.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanDaPan1.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanDaPan1.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanDaPan1.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanDaPan1.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanDaPan1.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanDaPan1.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanDaPan1.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanDaPan1.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanDaPan1.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanDaPan1.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanDaPan1.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanDaPan1.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanDaPan1.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanDaPan1.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanDaPan1.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanDaPan1.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanDaPan1.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanDaPan1.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanDaPan1.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanDaPan1.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanDaPan1.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanDaPan1.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanDaPan1.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanDaPan1.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanDaPan1.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPanDaPan1.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPanDaPan1.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanDaPan1;
    }

    public static StockDayYanPanChunJishu getChunJishuentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanChunJishu stockDayYanPanChunJishu = new StockDayYanPanChunJishu();
        stockDayYanPanChunJishu.setKdj(upups[0]);
        stockDayYanPanChunJishu.setMacd(upups[1]);
        stockDayYanPanChunJishu.setQuantityMa(upups[2]);
        stockDayYanPanChunJishu.setPriceMa(upups[3]);
        stockDayYanPanChunJishu.setRsi(upups[4]);
        stockDayYanPanChunJishu.setWr(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPanChunJishu.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanChunJishu.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanChunJishu.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanChunJishu.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanChunJishu.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanChunJishu.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanChunJishu.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanChunJishu.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanChunJishu.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanChunJishu.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanChunJishu.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanChunJishu.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanChunJishu.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanChunJishu.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanChunJishu.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanChunJishu.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanChunJishu.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanChunJishu.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanChunJishu.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanChunJishu.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanChunJishu.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanChunJishu.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanChunJishu.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanChunJishu.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanChunJishu.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanChunJishu.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanChunJishu.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanChunJishu.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanChunJishu.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanChunJishu.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPanChunJishu.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPanChunJishu.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanChunJishu;
    }

    public static StockDayYanPanChunTuxing getChunTuxingentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanChunTuxing stockDayYanPanChunTuxing = new StockDayYanPanChunTuxing();
        stockDayYanPanChunTuxing.setDangRi(upups[0]);
        stockDayYanPanChunTuxing.setLiangXian(upups[1]);
        stockDayYanPanChunTuxing.setSanXian(upups[2]);
        stockDayYanPanChunTuxing.setSiXian(upups[3]);
        stockDayYanPanChunTuxing.setWuXian(upups[4]);
        stockDayYanPanChunTuxing.setDuoXian(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanChunTuxing.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanChunTuxing.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanChunTuxing.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanChunTuxing.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanChunTuxing.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanChunTuxing.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPanChunTuxing.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPanChunTuxing.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanChunTuxing;
    }

    public static StockDayYanPanZhuYanJiShu getZhuYanJiShuentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanZhuYanJiShu stockDayYanPanZhuYanJiShu = new StockDayYanPanZhuYanJiShu();
        stockDayYanPanZhuYanJiShu.setPriceAndMaRelation(upups[0]);
        stockDayYanPanZhuYanJiShu.setLiangXian(upups[1]);
        stockDayYanPanZhuYanJiShu.setSanXian(upups[2]);
        stockDayYanPanZhuYanJiShu.setKdj(upups[3]);
        stockDayYanPanZhuYanJiShu.setMacd(upups[4]);
        stockDayYanPanZhuYanJiShu.setPriceMa(upups[5]);
        String[] lingsi = upups[6].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanZhuYanJiShu.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[60].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[61].split(",");
        stockDayYanPanZhuYanJiShu.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanZhuYanJiShu;
    }


}
