package com.stock.stockday.util;


import com.stock.stockday.model.StockDayYanPanKMAQ20;
import com.stock.stockday.model.StockDayYanPanKMPTD;
import com.stock.stockday.model.StockDayYanPanKTu20L;
import com.stock.stockday.model.StockDayYanPanKTu20LS;
import com.stock.stockday.model.StockDayYanPanKTu20S;
import com.stock.stockday.model.StockDayYanPanKmQR;
import com.stock.stockday.model.StockDayYanPanQTuXing;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import static com.stock.stockday.util.getBigDecimalUtil.getBigDecimal;

public class NewGetEntity {

    public static StockDayYanPanKMPTD getKMPTDentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanKMPTD stockDayYanPanKMPTD = new StockDayYanPanKMPTD();
        stockDayYanPanKMPTD.setPriceAndMaRelation(upups[0]);
        stockDayYanPanKMPTD.setQian20TuXing(upups[1]);
        stockDayYanPanKMPTD.setKdj(upups[2]);
        stockDayYanPanKMPTD.setPriceMa(upups[3]);
        String[] lingsi = upups[4].split(",");
        stockDayYanPanKMPTD.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanKMPTD.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanKMPTD.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanKMPTD.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanKMPTD.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanKMPTD.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanKMPTD.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanKMPTD.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanKMPTD.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanKMPTD.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanKMPTD.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanKMPTD.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanKMPTD.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanKMPTD.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanKMPTD.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanKMPTD.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanKMPTD.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanKMPTD.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanKMPTD.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanKMPTD.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanKMPTD.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanKMPTD.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanKMPTD.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanKMPTD.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanKMPTD.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanKMPTD.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanKMPTD.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanKMPTD.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanKMPTD.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanKMPTD.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanKMPTD.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanKMPTD.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanKMPTD;
    }

    public static StockDayYanPanKTu20LS getKTu20LSentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanKTu20LS stockDayYanPanKTu20LS = new StockDayYanPanKTu20LS();
        stockDayYanPanKTu20LS.setLiangXian(upups[0]);
        stockDayYanPanKTu20LS.setSanXian(upups[1]);
        stockDayYanPanKTu20LS.setQian20TuXing(upups[2]);
        stockDayYanPanKTu20LS.setKdj(upups[3]);
        String[] lingsi = upups[4].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanKTu20LS.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanKTu20LS.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanKTu20LS.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanKTu20LS.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanKTu20LS.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanKTu20LS.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanKTu20LS.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanKTu20LS.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanKTu20LS;
    }

    public static StockDayYanPanKTu20S getKTu20Sentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanKTu20S stockDayYanPanKTu20S = new StockDayYanPanKTu20S();
        stockDayYanPanKTu20S.setSanXian(upups[0]);
        stockDayYanPanKTu20S.setQian20TuXing(upups[1]);
        stockDayYanPanKTu20S.setKdj(upups[2]);
        String[] lingsi = upups[3].split(",");
        stockDayYanPanKTu20S.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[4].split(",");
        stockDayYanPanKTu20S.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanKTu20S.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanKTu20S.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanKTu20S.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanKTu20S.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanKTu20S.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanKTu20S.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanKTu20S.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanKTu20S.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanKTu20S.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanKTu20S.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanKTu20S.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanKTu20S.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanKTu20S.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanKTu20S.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanKTu20S.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanKTu20S.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanKTu20S.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanKTu20S.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanKTu20S.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanKTu20S.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanKTu20S.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanKTu20S.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanKTu20S.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanKTu20S.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanKTu20S.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanKTu20S.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanKTu20S.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanKTu20S.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanKTu20S.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanKTu20S.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanKTu20S;
    }

    public static StockDayYanPanKTu20L getKTu20Lentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanKTu20L stockDayYanPanKTu20L = new StockDayYanPanKTu20L();
        stockDayYanPanKTu20L.setLiangXian(upups[0]);
        stockDayYanPanKTu20L.setQian20TuXing(upups[1]);
        stockDayYanPanKTu20L.setKdj(upups[2]);
        String[] lingsi = upups[3].split(",");
        stockDayYanPanKTu20L.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[4].split(",");
        stockDayYanPanKTu20L.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanKTu20L.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanKTu20L.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanKTu20L.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanKTu20L.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanKTu20L.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanKTu20L.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanKTu20L.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanKTu20L.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanKTu20L.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanKTu20L.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanKTu20L.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanKTu20L.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanKTu20L.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanKTu20L.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanKTu20L.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanKTu20L.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanKTu20L.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanKTu20L.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanKTu20L.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanKTu20L.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanKTu20L.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanKTu20L.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanKTu20L.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanKTu20L.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanKTu20L.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanKTu20L.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanKTu20L.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanKTu20L.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanKTu20L.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanKTu20L.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanKTu20L;
    }

    public static StockDayYanPanKMAQ20 getKMAQ20entity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanKMAQ20 stockDayYanPanKMAQ20 = new StockDayYanPanKMAQ20();
        stockDayYanPanKMAQ20.setQian20TuXing(upups[0]);
        stockDayYanPanKMAQ20.setKdj(upups[1]);
        stockDayYanPanKMAQ20.setPriceMa(upups[2]);
        String[] lingsi = upups[3].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[4].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanKMAQ20.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanKMAQ20.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanKMAQ20.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanKMAQ20.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanKMAQ20.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanKMAQ20.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanKMAQ20.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanKMAQ20.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanKMAQ20;
    }

    public static StockDayYanPanKmQR getKmQRentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanKmQR stockDayYanPanKmQR = new StockDayYanPanKmQR();
        stockDayYanPanKmQR.setKdj(upups[0]);
        stockDayYanPanKmQR.setMacd(upups[1]);
        stockDayYanPanKmQR.setQuantityMa(upups[2]);
        stockDayYanPanKmQR.setRsi(upups[3]);
        String[] lingsi = upups[4].split(",");
        stockDayYanPanKmQR.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanKmQR.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanKmQR.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanKmQR.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanKmQR.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanKmQR.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanKmQR.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanKmQR.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanKmQR.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanKmQR.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanKmQR.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanKmQR.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanKmQR.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanKmQR.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanKmQR.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanKmQR.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanKmQR.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanKmQR.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanKmQR.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanKmQR.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanKmQR.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanKmQR.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanKmQR.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanKmQR.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanKmQR.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanKmQR.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanKmQR.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanKmQR.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanKmQR.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanKmQR.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanKmQR.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanKmQR.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanKmQR.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanKmQR.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanKmQR.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanKmQR.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanKmQR.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanKmQR.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanKmQR.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanKmQR.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanKmQR.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanKmQR.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanKmQR.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanKmQR.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanKmQR.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanKmQR.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanKmQR.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanKmQR.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanKmQR.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanKmQR.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanKmQR.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanKmQR.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanKmQR.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanKmQR.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanKmQR.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[59].split(",");
        stockDayYanPanKmQR.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanKmQR;
    }

    public static StockDayYanPanQTuXing getQTuXingentity(String path) throws IOException {
        InputStream inStream = new FileInputStream(path + ".txt"); //读入原文件
        BufferedReader reader = new BufferedReader(new InputStreamReader(inStream, "UTF-8"));
        StringBuffer stringBuffer = new StringBuffer();
        String line;
        String upup;
        while ((line = reader.readLine()) != null) {
            stringBuffer.append(line);
        }
        reader.close();
        upup = stringBuffer.toString();
        String[] upups = upup.split("—");
        StockDayYanPanQTuXing stockDayYanPanQTuXing= new StockDayYanPanQTuXing();
        stockDayYanPanQTuXing.setDangRi(upups[0]);
        stockDayYanPanQTuXing.setSanXian(upups[1]);
        stockDayYanPanQTuXing.setQian20TuXing(upups[2]);
        String[] lingsi = upups[3].split(",");
        stockDayYanPanQTuXing.setShangZhangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[4].split(",");
        stockDayYanPanQTuXing.setShangZhangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[5].split(",");
        stockDayYanPanQTuXing.setShangZhangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[6].split(",");
        stockDayYanPanQTuXing.setShangZhangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[7].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum1(getBigDecimal(lingsi[1]));
        lingsi = upups[8].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa1(getBigDecimal(lingsi[1]));
        lingsi = upups[9].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount1(getBigDecimal(lingsi[1]));
        lingsi = upups[10].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate1(getBigDecimal(lingsi[1]));
        lingsi = upups[11].split(",");
        stockDayYanPanQTuXing.setShangZhangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[12].split(",");
        stockDayYanPanQTuXing.setShangZhangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[13].split(",");
        stockDayYanPanQTuXing.setShangZhangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[14].split(",");
        stockDayYanPanQTuXing.setShangZhangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[15].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum2(getBigDecimal(lingsi[1]));
        lingsi = upups[16].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa2(getBigDecimal(lingsi[1]));
        lingsi = upups[17].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount2(getBigDecimal(lingsi[1]));
        lingsi = upups[18].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate2(getBigDecimal(lingsi[1]));
        lingsi = upups[19].split(",");
        stockDayYanPanQTuXing.setShangZhangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[20].split(",");
        stockDayYanPanQTuXing.setShangZhangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[21].split(",");
        stockDayYanPanQTuXing.setShangZhangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[22].split(",");
        stockDayYanPanQTuXing.setShangZhangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[23].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum3(getBigDecimal(lingsi[1]));
        lingsi = upups[24].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa3(getBigDecimal(lingsi[1]));
        lingsi = upups[25].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount3(getBigDecimal(lingsi[1]));
        lingsi = upups[26].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate3(getBigDecimal(lingsi[1]));
        lingsi = upups[27].split(",");
        stockDayYanPanQTuXing.setShangZhangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[28].split(",");
        stockDayYanPanQTuXing.setShangZhangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[29].split(",");
        stockDayYanPanQTuXing.setShangZhangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[30].split(",");
        stockDayYanPanQTuXing.setShangZhangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[31].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum5(getBigDecimal(lingsi[1]));
        lingsi = upups[32].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa5(getBigDecimal(lingsi[1]));
        lingsi = upups[33].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount5(getBigDecimal(lingsi[1]));
        lingsi = upups[34].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate5(getBigDecimal(lingsi[1]));
        lingsi = upups[35].split(",");
        stockDayYanPanQTuXing.setShangZhangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[36].split(",");
        stockDayYanPanQTuXing.setShangZhangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[37].split(",");
        stockDayYanPanQTuXing.setShangZhangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[38].split(",");
        stockDayYanPanQTuXing.setShangZhangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[39].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum8(getBigDecimal(lingsi[1]));
        lingsi = upups[40].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa8(getBigDecimal(lingsi[1]));
        lingsi = upups[41].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount8(getBigDecimal(lingsi[1]));
        lingsi = upups[42].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate8(getBigDecimal(lingsi[1]));
        lingsi = upups[43].split(",");
        stockDayYanPanQTuXing.setShangZhangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[44].split(",");
        stockDayYanPanQTuXing.setShangZhangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[45].split(",");
        stockDayYanPanQTuXing.setShangZhangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[46].split(",");
        stockDayYanPanQTuXing.setShangZhangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[47].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum13(getBigDecimal(lingsi[1]));
        lingsi = upups[48].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa13(getBigDecimal(lingsi[1]));
        lingsi = upups[49].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount13(getBigDecimal(lingsi[1]));
        lingsi = upups[50].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate13(getBigDecimal(lingsi[1]));
        lingsi = upups[51].split(",");
        stockDayYanPanQTuXing.setShangZhangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[52].split(",");
        stockDayYanPanQTuXing.setShangZhangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[53].split(",");
        stockDayYanPanQTuXing.setShangZhangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[54].split(",");
        stockDayYanPanQTuXing.setShangZhangRate20(getBigDecimal(lingsi[1]));
        lingsi = upups[55].split(",");
        stockDayYanPanQTuXing.setXiaJiangSum20(getBigDecimal(lingsi[1]));
        lingsi = upups[56].split(",");
        stockDayYanPanQTuXing.setXiaJiangMa20(getBigDecimal(lingsi[1]));
        lingsi = upups[57].split(",");
        stockDayYanPanQTuXing.setXiaJiangCount20(getBigDecimal(lingsi[1]));
        lingsi = upups[58].split(",");
        stockDayYanPanQTuXing.setXiaJiangRate20(getBigDecimal(lingsi[1]));
        return stockDayYanPanQTuXing;
    }
}
